# Generated by Django 5.0.4 on 2024-07-09 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vstutils_api', '0006_fix_user_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomTranslations',
        ),
    ]
