export const SET_ACTIVE_COMPONENT = 'SET_ACTIVE_COMPONENT';
export const CREATE_COMPONENT_STATE = 'CREATE_COMPONENT_STATE';
export const DESTROY_COMPONENT_STATE = 'DESTROY_COMPONENT_STATE';
export const INIT_COMPONENT_STATE = 'INIT_COMPONENT_STATE';
export const COMPONENTS_MODULE_NAME = 'componentsStore';
