# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_proj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('hidden', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=1024)),
                ('hosts', models.ManyToManyField(to='test_proj.Host')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='subgroups', to='test_proj.HostGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
