# Generated by Django 2.2.4 on 2019-08-30 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_proj', '0002_hostgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('name', models.CharField(max_length=1024)),
                ('for_order1', models.IntegerField()),
                ('for_order2', models.IntegerField()),
                ('origin_pos', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('value', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='hostgroup',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', related_query_name='subgroups', to='test_proj.HostGroup'),
        ),
        migrations.CreateModel(
            name='ModelWithFK',
            fields=[
                ('id', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('hidden', models.BooleanField(default=False)),
                ('some_fk', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_proj.Host')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
