# Generated by Django 2.2.4 on 2019-09-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_proj', '0003_auto_20190830_0228'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelWithBinaryFiles',
            fields=[
                ('id', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('hidden', models.BooleanField(default=False)),
                ('some_binfile', models.TextField(default='')),
                ('some_binimage', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
