# Generated by Django 2.2.2 on 2019-09-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_proj', '0004_modelwithbinaryfiles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelwithbinaryfiles',
            old_name='some_binimage',
            new_name='some_namedbinimage',
        ),
        migrations.AddField(
            model_name='modelwithbinaryfiles',
            name='some_namedbinfile',
            field=models.TextField(default=''),
        ),
    ]
