# Generated by Django 2.2.13 on 2020-08-20 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_proj', '0007_varbasedmodel_variable'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelwithfk',
            name='multiselect',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='modelwithfk',
            name='no_prefetch_and_link_fk',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ModelWithFK2', to='test_proj.Host'),
        ),
    ]
