# Generated by Django 2.2.16 on 2020-10-20 02:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test_proj', '0008_auto_20200820_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('hidden', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=256)),
                ('registerDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'default_related_name': 'author',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('hidden', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='test_proj.Author')),
            ],
            options={
                'default_related_name': 'post',
            },
        ),
        migrations.CreateModel(
            name='ExtraPost',
            fields=[
            ],
            options={
                'proxy': True,
                'default_related_name': 'post',
                'indexes': [],
                'constraints': [],
            },
            bases=('test_proj.post',),
        ),
    ]
