# Generated by Django 2.2.16 on 2020-12-14 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_proj', '0009_author_extrapost_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableType',
            fields=[
                ('id', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('hidden', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=128)),
                ('val_type', models.CharField(max_length=128)),
            ],
            options={
                'default_related_name': 'vartypes',
            },
        ),
        migrations.AddField(
            model_name='variable',
            name='key',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='test_proj.VariableType'),
        ),
    ]
