# Generated by Django 2.2.18 on 2021-02-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_proj', '0012_auto_20210127_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelwithbinaryfiles',
            name='some_filefield',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='modelwithbinaryfiles',
            name='some_imagefield',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
