# Generated by Django 2.2.19 on 2021-03-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_proj', '0013_auto_20210226_0512'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListOfFiles',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('updated', models.DateTimeField()),
            ],
        ),
    ]
