# Generated by Django 2.2.18 on 2021-03-15 05:10

from django.db import migrations
import django.db.models.deletion
import vstutils.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('test_proj', '0014_listoffiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverridenModelWithBinaryFiles',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('test_proj.modelwithbinaryfiles',),
        ),
        migrations.AddField(
            model_name='modelwithbinaryfiles',
            name='some_FkModelfield',
            field=vstutils.models.fields.FkModelField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_proj.Author'),
        ),
        migrations.AlterField(
            model_name='modelwithbinaryfiles',
            name='some_multiplenamedbinfile',
            field=vstutils.models.fields.MultipleNamedBinaryFileInJSONField(default=''),
        ),
        migrations.AlterField(
            model_name='modelwithbinaryfiles',
            name='some_multiplenamedbinimage',
            field=vstutils.models.fields.MultipleNamedBinaryImageInJSONField(default=''),
        ),
        migrations.AlterField(
            model_name='modelwithbinaryfiles',
            name='some_namedbinfile',
            field=vstutils.models.fields.NamedBinaryFileInJSONField(default=''),
        ),
        migrations.AlterField(
            model_name='modelwithbinaryfiles',
            name='some_namedbinimage',
            field=vstutils.models.fields.NamedBinaryImageInJSONField(default=''),
        ),
        migrations.AlterField(
            model_name='modelwithbinaryfiles',
            name='some_validatedmultiplenamedbinimage',
            field=vstutils.models.fields.MultipleNamedBinaryImageInJSONField(default=''),
        ),
        migrations.AlterField(
            model_name='modelwithbinaryfiles',
            name='some_validatednamedbinimage',
            field=vstutils.models.fields.NamedBinaryImageInJSONField(default=''),
        ),
    ]
