# Generated by Django 2.2.18 on 2021-04-07 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_proj', '0015_auto_20210315_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelwithfk',
            name='fk_with_filters',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_proj.Post'),
        ),
    ]
