# Generated by Django 3.2 on 2021-04-28 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_proj', '0017_auto_20210428_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeepNestedModel',
            fields=[
                ('id', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('hidden', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=10)),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deepnested', to='test_proj.deepnestedmodel')),
            ],
            options={
                'default_related_name': 'deepnested',
            },
        ),
    ]
