# Generated by Django 3.2 on 2021-05-17 04:59

from django.db import migrations, models
import django.db.models.deletion
import vstutils.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('test_proj', '0019_auto_20210514_0426'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelForCheckFileAndImageField',
            fields=[
                ('id', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('hidden', models.BooleanField(default=False)),
                ('some_image_field', models.ImageField(default='', upload_to='')),
                ('some_file_field', models.FileField(default='', upload_to='')),
                ('some_multiple_image_field', vstutils.models.fields.MultipleImageField(default='', upload_to='')),
                ('some_multiple_file_field', vstutils.models.fields.MultipleFileField(default='', upload_to='')),
                ('some_json_field', models.JSONField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='modelwithbinaryfiles',
            options={'default_related_name': 'rel_model'},
        ),
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='modelwithbinaryfiles',
            name='some_FkModelfield',
            field=vstutils.models.fields.FkModelField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_model', to='test_proj.author'),
        ),
        migrations.AddField(
            model_name='modelwithbinaryfiles',
            name='related_model',
            field=models.ManyToManyField(related_name='rel_models', to='test_proj.ModelForCheckFileAndImageField'),
        ),
    ]
