# Generated by Django 3.2 on 2021-06-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_proj', '0021_readonlydeepnestedmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachableModel',
            fields=[
                ('id', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('hidden', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
    ]
