# Generated by Django 3.2 on 2021-06-11 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_proj', '0022_cachablemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachableProxyModel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('test_proj.cachablemodel',),
        ),
    ]
