# Generated by Django 3.2.8 on 2021-10-27 06:07

from django.db import migrations, models
import vstutils.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('test_proj', '0025_author_decimal'),
    ]

    operations = [
        migrations.CreateModel(
            name='SomethingWithImage',
            fields=[
                ('id', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('hidden', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('validimage', vstutils.models.fields.NamedBinaryImageInJSONField(default='')),
                ('invalidimage', vstutils.models.fields.NamedBinaryImageInJSONField(default='')),
                ('imagewithmarginapplying', vstutils.models.fields.NamedBinaryImageInJSONField(default='')),
            ],
        ),
    ]
