# Generated by Django 3.2 on 2021-10-28 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_proj', '0026_somethingwithimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangedPkField',
            fields=[
                ('hidden', models.BooleanField(default=False)),
                ('id', models.TextField(blank=True, null=True)),
                ('reg_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelWithChangedFk',
            fields=[
                ('id', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('hidden', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=10)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_proj.changedpkfield')),
            ],
        ),
    ]
