# Generated by Django 3.2.3 on 2021-11-24 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_proj', '0028_auto_20211119_0250'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicFields',
            fields=[
                ('id', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('hidden', models.BooleanField(default=False)),
                ('field_type', models.CharField(max_length=100)),
                ('dynamic_with_types', models.CharField(max_length=500)),
            ],
        ),
    ]
