# Generated by Django 3.2.11 on 2022-02-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_proj', '0029_dynamicfields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('parents', models.ManyToManyField(related_name='groups', related_query_name='childrens', to='test_proj.Group')),
            ],
            options={
                'default_related_name': 'groups',
            },
        ),
    ]
