# Generated by Django 3.2.11 on 2022-02-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_proj', '0030_auto_20220210_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cachablemodel',
            name='hidden',
        ),
        migrations.AlterField(
            model_name='cachablemodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
