# Generated by Django 3.2.12 on 2022-02-21 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_proj', '0031_auto_20220217_0631'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelWithNestedModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='parents',
            field=models.ManyToManyField(related_name='childrens', to='test_proj.Group'),
        ),
        migrations.CreateModel(
            name='GroupWithFK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('fkmodel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupswithfk', to='test_proj.modelwithnestedmodels')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='test_proj.groupwithfk')),
            ],
            options={
                'default_related_name': 'groupswithfk',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='fkmodel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='test_proj.modelwithnestedmodels'),
        ),
    ]
