# Generated by Django 3.2.11 on 2022-02-28 07:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('test_proj', '0032_auto_20220221_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelWithUuid',
            fields=[
                ('hidden', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('data', models.CharField(max_length=256)),
            ],
            options={
                'default_related_name': 'model_with_uuid',
            },
        ),
    ]
