# Generated by Django 3.2.12 on 2022-04-19 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_proj', '0035_auto_20220418_0517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='detail_information',
        ),
    ]
