# Generated by Django 3.2.15 on 2022-10-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_proj', '0036_remove_author_detail_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelWithCrontabField',
            fields=[
                ('id', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('hidden', models.BooleanField(default=False)),
                ('cron', models.CharField(max_length=64)),
            ],
        ),
    ]
