# Generated by Django 3.2.15 on 2022-11-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_proj', '0037_modelwithcrontabfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectedBySignal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('fkmodel', models.ManyToManyField(related_name='protected', to='test_proj.ModelWithNestedModels')),
            ],
            options={
                'default_related_name': 'protected',
            },
        ),
    ]
