# Generated by Django 3.2.16 on 2023-01-16 07:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('test_proj', '0038_protectedbysignal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelWithUuidPk',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelWithUuidFK',
            fields=[
                ('id', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('hidden', models.BooleanField(default=False)),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_proj.modelwithuuidpk')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
