# Generated by Django 4.1.5 on 2023-01-30 09:26

from django.db import migrations, models
import django.db.models.deletion
import vstutils.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('test_proj', '0039_modelwithuuidfk_modelwithuuidpk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_proj.category'),
        ),
        migrations.AlterField(
            model_name='deepnestedmodel',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_proj.deepnestedmodel'),
        ),
        migrations.AlterField(
            model_name='group',
            name='fkmodel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_proj.modelwithnestedmodels'),
        ),
        migrations.AlterField(
            model_name='groupwithfk',
            name='fkmodel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_proj.modelwithnestedmodels'),
        ),
        migrations.AlterField(
            model_name='modelwithbinaryfiles',
            name='some_FkModelfield',
            field=vstutils.models.fields.FkModelField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_proj.author'),
        ),
        migrations.AlterField(
            model_name='modelwithuuidfk',
            name='fk',
            field=vstutils.models.fields.FkModelField(on_delete=django.db.models.deletion.CASCADE, to='test_proj.modelwithuuidpk'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_proj.author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_proj.category'),
        ),
        migrations.AlterField(
            model_name='protectedbysignal',
            name='fkmodel',
            field=models.ManyToManyField(to='test_proj.modelwithnestedmodels'),
        ),
        migrations.AlterField(
            model_name='readonlydeepnestedmodel',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_proj.readonlydeepnestedmodel'),
        ),
    ]
