# Generated by Django 4.1.6 on 2023-02-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_proj', '0040_alter_category_parent_alter_deepnestedmodel_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='referer',
            field=models.IntegerField(null=True),
        ),
    ]
