# Generated by Django 4.2.2 on 2023-06-15 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_proj', '0041_author_referer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestExternalCustomModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('test_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
