# Generated by Django 4.2.11 on 2024-03-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_proj', '0043_manufacturer_store_product_option_manufacturer_store_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(models.F('name'), models.F('store'), name='uniq_name_store'),
        ),
    ]
