# Generated by Django 5.0.3 on 2024-03-19 05:01

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_proj', '0044_product_uniq_name_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicfields',
            name='generated_field',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Upper('field_type'), output_field=models.CharField(max_length=100)),
        ),
    ]
