import VueRouter from 'vue-router';
import { signals } from '@/vstutils/signals';

export default class RouterConstructor {
    /**
     * Constructor of RouterConstructor Class.
     * @param {Map<string, IView>} views Map with views objects.
     * generated by View class and having description in OpenAPI Schema.
     */
    constructor(views) {
        this.views = views;
        this.routes = this.formAllRoutes();
    }

    /**
     * Method, that returns array of routes objects, existing in current App.
     * @return {array} Routes Array.
     */
    getRoutes() {
        return this.routes;
    }

    /**
     * Method, that forms array of all routes objects, existing in current App.
     * @return {array} Routes Array.
     */
    formAllRoutes() {
        let routes = [];

        routes = routes.concat(this.formRoutesBasedOnViews());

        signals.emit('allRoutes.created', routes);

        return routes;
    }

    /**
     * Method, that forms array of routes objects, existing in current App, and based on App Views, that have description in OpenAPI Schema (this.views).
     * @return {array} Routes Array.
     */
    formRoutesBasedOnViews() {
        let routes = [];

        for (let view of this.views.values()) {
            if (view.hidden) continue;
            routes.push(view.toRoute());
            this.emitSignalAboutRouteCreation(routes.last);
        }

        return routes;
    }

    /**
     * Method emits signal: "route was created".
     * @param {object} route Object with route properties (name, path, component).
     */
    emitSignalAboutRouteCreation(route) {
        signals.emit('routes[' + route.name + '].created', route);
    }

    /**
     * Method, that returns new instance of VueRouter.
     * @return {VueRouter}
     */
    getRouter() {
        return new VueRouter({
            routes: this.getRoutes(),
        });
    }
}
